### ISSUE TITLE
Doesn't work properly with Sub-State Machine transitions (grey ones).

### ISSUE THREAD

**Issue by EldarHajiyev** [qwe321qwe321qwe321/Unity-AnimatorTransitionCopier#5]
Unity 2021.3.6f1
Some times it just doesn't paste.
And other times it throws error (was not able to replicate therefore don't have error log).
Tested inside other Sub-State Machine

**Comment by qwe321qwe321qwe321** [comment]
Can you show me the animator view or the animator controller file to reproduce the issue?

**Comment by EldarHajiyev** [comment]
Animator example:
https://drive.google.com/file/d/1aKFwrFG3w2B07AvX5cqKNbhs0biayGdK/view?usp=sharing

https://user-images.githubusercontent.com/90186435/218004999-56593563-30a3-492f-81d7-52eac9833dee.mp4

**Comment by qwe321qwe321qwe321** [comment]
> Animator example: https://drive.google.com/file/d/1aKFwrFG3w2B07AvX5cqKNbhs0biayGdK/view?usp=sharing

The issue should now be solved. Please try again and let me know if there are any further problems.
